# Message Of The Day
motd=Beiop ~Cakewars~
# Show The MineCon Badge Next To MOTD In Server List
show-minecon-badge=false
# Game Mode (0 = Survival, 1 = Creative)
game-mode=0
# Port
port=19137
# World Seed (Blank = Random Seed)
seed=
# Force Mob Spawning (false = Disabled, true = Enabled)
force-mob-spawning=false
# Peaceful Mode (false = Disabled, true = Enabled)
peaceful-mode=false
# World To Select
world-name=cakewars
# Maximum Player Count
max-players=8
# Enable Whitelist
whitelist=false
# Enable Death Messages
death-messages=true
# Generate Caves
generate-caves=true
